u

diff --git a/fin-bin/sandbox b/fin-bin/sandbox
--- a/fin-bin/sandbox
+++ b/fin-bin/sandbox
@@ -29,16 +29,16 @@ if [ -z "$1" ]
     exit 1
 fi
 
-if [ ! -d ".docksal" ]; then
-  echo-red "Cannot detect project root. Please make sure you run the sandbox command from a Dockal project's root folder."
-  exit 1
-fi
-
 # If top level domain is not given, set a default one
 if [ -z "$2" ]; then
   CUSTOMDOMAIN="gtacty.co"
 else
   CUSTOMDOMAIN="$2"
+fi
+
+if [ ! -d ".docksal" ]; then
+  echo-red "Cannot detect project root. Please make sure you run the sandbox command from a Dockal project's root folder."
+  exit 1
 fi
 
 # Lowercase the branch name for consistency
