s

diff --git a/fin-bin/sandbox b/fin-bin/sandbox
--- a/fin-bin/sandbox
+++ b/fin-bin/sandbox
@@ -23,6 +23,11 @@ echo-yellow () { echo -e "${yellow}$1${NC}"; }
 
 #-------------------------- Execution --------------------------------
 
+if [ ! -d .docksal ]; then
+  echo-red "Cannot detect project root. Please make sure you run the sandbox command from a Dockal project's root folder."
+  exit 1
+fi
+
 if [ -z "$1" ]
   then
     echo "No argument supplied"
